### ISSUE TITLE
armv6 / armv7 version

### ISSUE THREAD

**Issue by jvandenbroek** [maretodoric/theengsgateway-docker#1]
Could you create a build for armv6/7? Many thanks!

**Comment by maretodoric** [comment]
Sure, give me a day or two just ti figure out some kinks. There is a build problem for cmake while installing TheengsGateway on python3.10 on armv7. Works fine (it seems) with python3.9.

I would prefer to keep python3.10 but if i cannot figure out the issue eventually I'll just push the changes with python3.9

**Comment by maretodoric** [comment]
Just managed to figure out that there seems to be an issue with python3.10 , cmake and arm. It just fails on pip install. I'll make sure to open issue to cmake but for now i have downgraded python to 3.9 and created separate images for armv7, armv7, i386.

Let me know if you have any questions

**Comment by jvandenbroek** [comment]
Wow nice you found a solution so quick, it's working great here on armv7! Will test later on armv6 but no doubt it works just fine as well :-) Thank you!

**Comment by jvandenbroek** [comment]
Seems to be an issue with armv6, can't find module TheengsGateway._decoder:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
   File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details
     return _get_module_details(pkg_main_name, error)
   File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
     __import__(pkg_name)
   File "/opt/venv/lib/python3.9/site-packages/TheengsGateway/__init__.py", line 26, in <module>
     from .ble_gateway import run
   File "/opt/venv/lib/python3.9/site-packages/TheengsGateway/ble_gateway.py", line 35, in <module>
     from ._decoder import decodeBLE, getProperties, getAttribute
 ModuleNotFoundError: No module named 'TheengsGateway._decoder'
```

**Comment by maretodoric** [comment]
That's odd, i haven't received any errors during build. And decoder comes packaged with TheengsGatewaay, and obviously it managed to start gateway.

What device you used ? I'll try to see if i can emulate.

**Comment by jvandenbroek** [comment]
RPi 1 B+ Linux 5.15.61+ #1579 Fri Aug 26 11:08:59 BST 2022 armv6l
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

No issues on arm64 and armv7.

**Comment by maretodoric** [comment]
Thanks!
I'm not sure if this is an issue during cross-compile when creating a docker image or just some incompatability with armv6 and TheengsGateway. I've opened up an issue with theengs - https://github.com/theengs/gateway/issues/59

Maybe we'll figure out where exactly is the problem. It seems that package is built just fine (otherwise image creation would fail due to exit code), even module is compiled, but not sure why it cannot be loaded, that's why i believe that it has something to do with theengs gw.

**Comment by mikeS7** [comment]
There are no linux/arm/v6 variant for python:3.9-slim-bullseye image.
For Raspberry Pi 1 Balena base images can be used as base.
`FROM balenalib/raspberry-pi-python:3.9-bullseye`
