### ISSUE TITLE
Starting on RPi Zero W ends up in an error every time

### ISSUE THREAD

**Issue by lepinkainen** [maretodoric/theengsgateway-docker#5]
`docker run --rm --network host -e MQTT_HOST=192.168.1.12 -v /var/run/dbus:/var/run/dbus --name TheengsGateway theengs/gateway`

```
Creating config at /root/theengsgw.conf ...
{
    "host": "192.168.1.12",
    "pass": "",
    "user": "",
    "port": 1883,
    "publish_topic": "home/TheengsGateway/BTtoMQTT",
    "subscribe_topic": "home/+/BTtoMQTT/undecoded",
    "presence_topic": "home/presence/TheengsGateway",
    "presence": false,
    "publish_all": true,
    "ble_scan_time": 60,
    "ble_time_between_scans": 60,
    "log_level": "DEBUG",
    "discovery": true,
    "hass_discovery": true,
    "discovery_topic": "homeassistant/sensor",
    "discovery_device_name": "TheengsGateway",
    "discovery_filter": "[IBEACON,GAEN,MS-CDP]",
    "scanning_mode": "active",
    "adapter": "hci0",
    "time_sync": "[]",
    "time_format": "0"
}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/venv/lib/python3.9/site-packages/TheengsGateway/__init__.py", line 27, in <module>
    from .ble_gateway import run
  File "/opt/venv/lib/python3.9/site-packages/TheengsGateway/ble_gateway.py", line 41, in <module>
    from TheengsDecoder import decodeBLE
  File "/opt/venv/lib/python3.9/site-packages/TheengsDecoder/__init__.py", line 1, in <module>
    from ._decoder import decodeBLE  # noqa: F401
ModuleNotFoundError: No module named 'TheengsDecoder._decoder'
```

**Comment by koenvervloesem** [comment]
There have been other reports like this:

- https://github.com/theengs/gateway/issues/59
- https://github.com/maretodoric/theengsgateway-docker/issues/1

It probably is an issue with the ARMv6 Docker image. What does `uname -a` give on your Raspberry Pi?

**Comment by lepinkainen** [comment]
`Linux raspberrypi 5.15.84+ #1613 Thu Jan 5 11:58:09 GMT 2023 armv6l GNU/Linux`

**Comment by orzechszek** [comment]
Issue still occuring on RasPi.

**Comment by koenvervloesem** [comment]
@orzechszek Can you show the full diagnostic information your Docker container is giving, including information from the installed package versions, Python version, and operating system?

**Comment by orzechszek** [comment]
@koenvervloesem , some info:

System: Linux raspberrypi 5.15.61+ #1579 Fri Aug 26 11:08:59 BST 2022 armv6l GNU/Linux
PYTHON_VERSION=3.11.7
TheengsGateway-1.3.0
TheengsDecoder-1.6.8

**Comment by orzechszek** [comment]
@koenvervloesem , any ideas? Do you need additional data ?

**Comment by 1technophile** [comment]
@orzechszek I'm reproducing the issue on a Pi Zero W with docker

**Comment by 1technophile** [comment]
As an alternative on pi zero I got it working with a virtual env + pip on Raspbian:
```
sudo apt update
sudo apt install python3-venv python3-pip
python3 -m venv ~/theengs_gateway_venv
source ~/theengs_gateway_venv/bin/activate
pip install TheengsGateway
```

You may need to wait several minutes at some steps

**Comment by orzechszek** [comment]
Installed with pip

```
Successfully installed TheengsDecoder-1.7.0 TheengsGateway-1.4.0 aiofiles-23.2.1 aiohttp-3.9.3 aiosignal-1.3.1 attrs-23.2.0 bleak-0.21.1 bluetooth-adapters-0.17.0 bluetooth-clocks-0.2.0 bluetooth-numbers-1.1.1 frozenlist-1.4.1 importlib-metadata-7.0.1 mac-vendor-lookup-0.1.12 multidict-6.0.5 paho-mqtt-2.0.0 pycryptodomex-3.20.0 typing-extensions-4.9.0 usb-devices-0.4.5 yarl-1.9.4 zipp-3.17.0
```
Started with systemd and command: python3 -m TheengsGateway -H 192.168.50.115 -D 0 -ll DEBUG -tb 5 -sd 10


After few minutes I'm getting:

```
Main process exited, code=killed, status=11/SEGV
systemd[1]: theengsgateway.service: Failed with result 'signal'.
systemd[1]: theengsgateway.service: Consumed 28.866s CPU time.
```

**Comment by 1technophile** [comment]
Does it start and scan devices before exiting ?

**Comment by orzechszek** [comment]
Yes, it's working fine for a while.

**Comment by 1technophile** [comment]
And when you launch with the command line does it works longer?

Mine seems to hold:
```
INFO:BLEGateway:Sent 89 messages to MQTT
INFO:BLEGateway:Sent 85 messages to MQTT
INFO:BLEGateway:Sent 81 messages to MQTT
INFO:BLEGateway:Sent 81 messages to MQTT
INFO:BLEGateway:Sent 89 messages to MQTT
INFO:BLEGateway:Sent 79 messages to MQTT
INFO:BLEGateway:Sent 81 messages to MQTT
INFO:BLEGateway:Sent 90 messages to MQTT
INFO:BLEGateway:Sent 88 messages to MQTT
INFO:BLEGateway:Sent 77 messages to MQTT
INFO:BLEGateway:Sent 83 messages to MQTT
INFO:BLEGateway:Sent 88 messages to MQTT
INFO:BLEGateway:Sent 75 messages to MQTT
INFO:BLEGateway:Sent 87 messages to MQTT
INFO:BLEGateway:Sent 76 messages to MQTT
INFO:BLEGateway:Sent 85 messages to MQTT
INFO:BLEGateway:Sent 78 messages to MQTT
INFO:BLEGateway:Sent 92 messages to MQTT
INFO:BLEGateway:Sent 85 messages to MQTT
INFO:BLEGateway:Sent 77 messages to MQTT
INFO:BLEGateway:Sent 75 messages to MQTT
INFO:BLEGateway:Sent 79 messages to MQTT
INFO:BLEGateway:Sent 82 messages to MQTT
INFO:BLEGateway:Sent 85 messages to MQTT
INFO:BLEGateway:Sent 77 messages to MQTT
INFO:BLEGateway:Sent 77 messages to MQTT
INFO:BLEGateway:Sent 79 messages to MQTT
INFO:BLEGateway:Sent 78 messages to MQTT
INFO:BLEGateway:Sent 76 messages to MQTT
INFO:BLEGateway:Sent 73 messages to MQTT
INFO:BLEGateway:Sent 88 messages to MQTT
INFO:BLEGateway:Sent 90 messages to MQTT
INFO:BLEGateway:Sent 77 messages to MQTT
INFO:BLEGateway:Sent 90 messages to MQTT
INFO:BLEGateway:Sent 78 messages to MQTT
INFO:BLEGateway:Sent 81 messages to MQTT
INFO:BLEGateway:Sent 82 messages to MQTT
INFO:BLEGateway:Sent 74 messages to MQTT
INFO:BLEGateway:Sent 72 messages to MQTT
INFO:BLEGateway:Sent 88 messages to MQTT
INFO:BLEGateway:Sent 74 messages to MQTT
INFO:BLEGateway:Sent 82 messages to MQTT
INFO:BLEGateway:Sent 75 messages to MQTT
INFO:BLEGateway:Sent 80 messages to MQTT
INFO:BLEGateway:Sent 76 messages to MQTT
INFO:BLEGateway:Sent 75 messages to MQTT
INFO:BLEGateway:Sent 65 messages to MQTT
INFO:BLEGateway:Sent 81 messages to MQTT
INFO:BLEGateway:Sent 79 messages to MQTT
INFO:BLEGateway:Sent 83 messages to MQTT
INFO:BLEGateway:Sent 74 messages to MQTT
INFO:BLEGateway:Sent 92 messages to MQTT
INFO:BLEGateway:Sent 81 messages to MQTT
INFO:BLEGateway:Sent 79 messages to MQTT
INFO:BLEGateway:Sent 93 messages to MQTT
INFO:BLEGateway:Sent 88 messages to MQTT
INFO:BLEGateway:Sent 86 messages to MQTT
INFO:BLEGateway:Sent 77 messages to MQTT
```

**Comment by orzechszek** [comment]
In my case, for more than 45min it's working fine for now.

**Comment by orzechszek** [comment]
@1technophile @koenvervloesem - any news with docker or systemd issues?

**Comment by 1technophile** [comment]
Tried building the docker with different configurations on pi zero (around 1h each time) with always the same issue. Whereas with a pip install on the same board it works directly.

**Comment by orzechszek** [comment]
Did you try to run Theengs as a service? Was it working  correctly ?

**Comment by orzechszek** [comment]
Hi,
Does anybody tried run it as service on RPi? In my case it's still failing. Docker is also unusable.

**Comment by mani76** [comment]
Hello, still same problem with Zero W 2
